apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: buildpack-nodejs-build
  namespace: demo
spec:
  source:
    url: https://github.com/shipwright-io/sample-nodejs
    contextDir: source-build
  strategy:
    name: buildpacks
    kind: ClusterBuildStrategy
  output:
    image: kind-registry:5000/snowdrop/sample-nodejs:latest