name: "Test using Pack CLI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux-pack-build:
    name: Linux - Pack CLI build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        builder-image: [ 'paketobuildpacks/builder:tiny' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Container Registry
        uses: Sgitario/setup-container-registry@v1

      - name: Install Pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      - name: Test Quarkus Getting Started using ${{ matrix.builder-image }}
        run: |
          CONTAINER_NAME=quarkus-pack-hello
          CONTAINER_IMAGE=$CONTAINER_REGISTRY_URL/$CONTAINER_NAME:1.0

          # Checkout
          git clone https://github.com/quarkusio/quarkus-quickstarts.git

          # Build image and push to the container registry
          pack build $CONTAINER_IMAGE \
            -e BP_NATIVE_IMAGE="false" \
            -e BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \
            -e BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar" \
            --path ./quarkus-quickstarts/getting-started \
            --builder ${{ matrix.builder-image }}

          # Run container
          docker run -d --rm --name $CONTAINER_NAME -p 8081:8080 $CONTAINER_IMAGE

          # Wait until app is running
          while ! docker logs $CONTAINER_NAME | grep -q "Installed features";
          do
              sleep 1
          done

          # Verify app is running
          RESULT=$(curl localhost:8081/hello/greeting/coder)
          docker rm -f $CONTAINER_NAME
          if [[ "$RESULT" != "hello coder" ]]
          then
            echo "Application failed to start"
            exit 1
          fi